apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 27.16.0
    helm:
      releaseName: prometheus
      values: |
       server:
        persistentVolume:
          enabled: true
          size: 20Gi
          storageClass: longhorn   # or your storage class
        service:
          type: ClusterIP          # use LoadBalancer if you want external access

        alertmanager:
          enabled: true             # disable for minimal setup

        pushgateway:
          enabled: false             # disable for minimal setup

        kube-state-metrics:
          enabled: false              # recommended to keep cluster metrics

        nodeExporter:
          enabled: false              # recommended, basic node metrics
  destination:
    name: "in-cluster"
    namespace: lgtm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

