apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 37.1.2
    helm:
      values: |
        additionalArguments:
          - --entrypoints.dns-udp.address=:53/udp
        metrics:
          prometheus:
            entryPoint: metrics
            addEntryPointLabels: true
            addServiceLabels: true
        serviceMonitor:
          enabled: true
          namespace: traefik          # where Traefik runs
          labels:
            release: prometheus       # label your Prometheus Operator watches
          interval: 15s
          scrapeTimeout: 10s
        ports:
          web:
            port: 80
            expose:
              default: true
          websecure:
            port: 443
            expose:
              default: true
            tls:
              enabled: true
          dns-server:
            port: 53
            expose:
              default: true
          dns-udp:
            port: 53
            expose:
              default: true
            protocol: UDP
        ingressRoute:
          dashboard:
            enabled: true
        gateway:
          annotations: 
            cert-manager.io/cluster-issuer: cf-issuer
          listeners:
            web:
              port: 80
              protocol: HTTP
              namespacePolicy: 
                from: All
            websecure:        
              port: 443
              protocol: HTTPS
              namespacePolicy:
                from: All
              mode: Terminate
              hostname: "*.joshuadallacqua.com"
              certificateRefs:    
                - name: jdal-com-tls
            apex-websecure:        
              port: 443
              protocol: HTTPS
              namespacePolicy:
                from: All
              mode: Terminate
              hostname: joshuadallacqua.com
              certificateRefs:    
                - name: jdal-com-tls
            dns-server:
              port: 53
              protocol: TCP
              namespacePolicy:
                from: All
        providers:
          kubernetesGateway:
            enabled: true
            experimentalChannel: true
          kubernetesCRD:
            allowCrossNamespace: true
        api:
          dashboard: true
  destination:
    name: "in-cluster"
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

